// Belts
export const FETCH_BELTS = "FETCH_BELTS";
export const BELT_SELECTED = "BELT_SELECTED";
export const FETCH_BELT_IMAGES = "FETCH_BELT_IMAGES";

// Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const SET_USER_AUTH_INFO = "SET_USER_AUTH_INFO";
export const SET_USER_DB_INFO = "SET_USER_DB_INFO";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
